name: webviz-subsurface

on:
  push:
    branches:
      - debugxtgeo

jobs:
  webviz-subsurface:
    runs-on: ubuntu-latest
    steps:
    - name: 📖 Checkout commit locally
      uses: actions/checkout@v2

    - name: 🐍 Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"

    - name: 📦 Install webviz-subsurface with dependencies
      run: |
        pip install --upgrade pip
        pip install "fmu-tools>=1.8"

    - name: 🧾 List all installed packages
      run: pip freeze
